### PR TITLE
feat: Add `prod()` translation for dbplyr

### PR DESCRIPTION
**Pull request by m-muecke**

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. What would a test for this and other functionality look like?

**Comment by m-muecke** [comment]
> Thanks. What would a test for this and other functionality look like?

I have added some tests for the current agg functions. What is the scope difference between the duckdb and the duckplyr package for `dplyr` translations, both seem to have overlap.

**Comment by krlmlr** [comment]
duckplyr is data frame in, data frame out, with full compatibility and fallback to dplyr if needed.

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
