### PR TITLE
fix: Align the argument order of `dbWriteTable()` with the DBI specs

### LINKED ISSUE #43: dbWriteTable's arguments order
The DBI document says:

> The following arguments are not part of the dbWriteTable() generic (to improve compatibility across backends) but are part of the DBI specification:
>
> - row.names (default: FALSE)
> - overwrite (default: FALSE)
> - append (default: FALSE)
> - field.types (default: NULL)
> - temporary (default: FALSE)
>
>They must be provided as named arguments. See the "Specification" and "Value" sections for details on their usage.

But now `dbWriteTable__duckdb_connection_character_data.frame` can specify these options without names.
I think we need to change the position of the dot dot dot `...`.

https://github.com/duckdb/duckdb-r/blob/8386b9cd53ad08660e00aa4f755ea7032ca25dff/R/dbWriteTable__duckdb_connection_character_data.frame.R#L9-L17

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #43

### CODE REVIEW

**Comment by eitsupi** [comment]
@krlmlr Is there any reason why this would not be merged? Is there anything I can do?

**Comment by krlmlr** [comment]
Thanks. Running revdepchecks now.

**Comment by krlmlr** [comment]
Uploaded results, one package has new failures. Could you please take a look?

**Comment by eitsupi** [comment]
> Uploaded results, one package has new failures. Could you please take a look?

I have looked and found that the results were also different in duckdb installed from R-universe, so I think this is due to a change in the order of the records returned by duckdb and this PR is irrelevant.
https://github.com/darwin-eu-dev/PatientProfiles/blob/97f8a26ffede8ce09c98aece9ca67c43fa97db28/tests/testthat/test-addCategories.R#L25-L30

**Comment by eitsupi** [comment]
I've send a PR for fix the test cases darwin-eu-dev/PatientProfiles#456.

**Comment by krlmlr** [comment]
Thanks, also for double-checking!

**Pull request merged**
