### PR TITLE
ci: Include checks for older versions of Windows

### LINKED ISSUE #109: windows 10 - cannot install on R 4.0.3
Not sure but latest release was failing for me using stand install and command line:

Error in system(sprintf("%s -Pg %s", nm, shQuote(f)), intern = TRUE) :
  '""' not found

command issued
```  
c:\Program Files\R\R-4.0.3\bin\R.exe" CMD INSTALL . 
```

```
....
"C:/rtools40/mingw64/bin/"g++  -std=gnu++17 -I"c:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG -Iinclude -I../inst/include -DDUCKDB_DISABLE_PRINT -DDUCKDB_R_BUILD -Iduckdb/src/include -Iduckdb/third_party/fmt/include -Iduckdb/third_party/fsst -Iduckdb/third_party/re2 -Iduckdb/third_party/miniz -Iduckdb/third_party/utf8proc/include -Iduckdb/third_party/utf8proc -Iduckdb/third_party/hyperloglog -Iduckdb/third_party/fastpforlib -Iduckdb/third_party/tdigest -Iduckdb/third_party/libpg_query/include -Iduckdb/third_party/libpg_query -Iduckdb/third_party/concurrentqueue -Iduckdb/third_party/pcg -Iduckdb/third_party/httplib -Iduckdb/third_party/fast_float -Iduckdb/third_party/mbedtls -Iduckdb/third_party/mbedtls/include -Iduckdb/third_party/mbedtls/library -Iduckdb/third_party/jaro_winkler -Iduckdb/third_party/jaro_winkler/details -Iduckdb/extension/parquet/include -Iduckdb/third_party/parquet -Iduckdb/third_party/snappy -Iduckdb/third_party/thrift -Iduckdb/third_party/zstd/include -I../inst/include -Iduckdb -DDUCKDB_EXTENSION_PARQUET_LINKED -DDUCKDB_BUILD_LIBRARY -DDUCKDB_PLATFORM_RTOOLS=1         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c types.cpp -o types.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++17 -I"c:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG -Iinclude -I../inst/include -DDUCKDB_DISABLE_PRINT -DDUCKDB_R_BUILD -Iduckdb/src/include -Iduckdb/third_party/fmt/include -Iduckdb/third_party/fsst -Iduckdb/third_party/re2 -Iduckdb/third_party/miniz -Iduckdb/third_party/utf8proc/include -Iduckdb/third_party/utf8proc -Iduckdb/third_party/hyperloglog -Iduckdb/third_party/fastpforlib -Iduckdb/third_party/tdigest -Iduckdb/third_party/libpg_query/include -Iduckdb/third_party/libpg_query -Iduckdb/third_party/concurrentqueue -Iduckdb/third_party/pcg -Iduckdb/third_party/httplib -Iduckdb/third_party/fast_float -Iduckdb/third_party/mbedtls -Iduckdb/third_party/mbedtls/include -Iduckdb/third_party/mbedtls/library -Iduckdb/third_party/jaro_winkler -Iduckdb/third_party/jaro_winkler/details -Iduckdb/extension/parquet/include -Iduckdb/third_party/parquet -Iduckdb/third_party/snappy -Iduckdb/third_party/thrift -Iduckdb/third_party/zstd/include -I../inst/include -Iduckdb -DDUCKDB_EXTENSION_PARQUET_LINKED -DDUCKDB_BUILD_LIBRARY -DDUCKDB_PLATFORM_RTOOLS=1         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c cpp11.cpp -o cpp11.o
**Error in system(sprintf("%s -Pg %s", nm, shQuote(f)), intern = TRUE) :
  '""' not found**
Calls: <Anonymous> -> lapply -> FUN -> strsplit -> system
Execution halted
make: *** [c:/PROGRA~1/R/R-40~1.3/share/make/winshlib.mk:32: symbols.rds] Error 1
ERROR: compilation failed for package 'duckdb'
* removing 'C:/Users/u365042/Documents/R/win-library/4.0/duckdb'
```

### LINKED ISSUE #113: Unable to build 0.10.0 from source for windows for R 4.1.2
I have been having trouble with timestamps and microseconds with duckdb 0.7.1 in R 4.1.2
(https://stackoverflow.com/questions/78187731/support-microseconds-when-storing-posixct-column-in-duckdb-file)

I thought I'd try the latest build to try to address it, but CRAN doesn't have a 4.1.2 windows binary available.

When I try to build it I get the following error:

```
* installing *source* package 'duckdb' ...
** package 'duckdb' successfully unpacked and MD5 sums checked
** using staged installation
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture

"C:/rtools40/mingw64/bin/"g++  -std=gnu++17 -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG -Iinclude -I../inst/include -DDUCKDB_DISABLE_PRINT -DDUCKDB_R_BUILD -Iduckdb/src/include -Iduckdb/third_party/fmt/include -Iduckdb/third_party/fsst -Iduckdb/third_party/re2 -Iduckdb/third_party/miniz -Iduckdb/third_party/utf8proc/include -Iduckdb/third_party/utf8proc -Iduckdb/third_party/hyperloglog -Iduckdb/third_party/skiplist -Iduckdb/third_party/fastpforlib -Iduckdb/third_party/tdigest -Iduckdb/third_party/libpg_query/include -Iduckdb/third_party/libpg_query -Iduckdb/third_party/concurrentqueue -Iduckdb/third_party/pcg -Iduckdb/third_party/httplib -Iduckdb/third_party/fast_float -Iduckdb/third_party/mbedtls -Iduckdb/third_party/mbedtls/include -Iduckdb/third_party/mbedtls/library -Iduckdb/third_party/jaro_winkler -Iduckdb/third_party/jaro_winkler/details -Iduckdb/extension/parquet/include -Iduckdb/third_party/parquet -Iduckdb/third_party/thrift -Iduckdb/third_party/snappy -Iduckdb/third_party/zstd/include -Iduckdb/third_party/mbedtls -Iduckdb/third_party/mbedtls/include -I../inst/include -Iduckdb -DDUCKDB_EXTENSION_PARQUET_LINKED -DDUCKDB_BUILD_LIBRARY -DDUCKDB_PLATFORM_RTOOLS=1         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c duckdb/ub_src_catalog.cpp -o duckdb/ub_src_catalog.o

...

In file included from duckdb/ub_src_common.cpp:39:
duckdb/src/common/local_file_system.cpp: In function 'std::__cxx11::string duckdb::AdditionalLockInfo(std::__cxx11::wstring)':
duckdb/src/common/local_file_system.cpp:698:8: error: 'QueryFullProcessImageNameW' was not declared in this scope
    if (QueryFullProcessImageNameW(process, 0, full_path, &full_path_size) && full_path_size <= MAX_PATH) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [C:/PROGRA~1/R/R-41~1.2/etc/x64/Makeconf:245: duckdb/ub_src_common.o] Error 1
ERROR: compilation failed for package 'duckdb'
* removing 'C:/_dev/R/win-library/4.0/duckdb'
```

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #109. Closes #113.

### CODE REVIEW

**Comment by krlmlr** [comment]
@Antonov548: Can you please propose a fix for building in R 4.0 (in the vendored sources)? You'll need the R version and an older version of Rtools.

An alternative is to guess what headers need to be added, and to let CI/CD do the checking, or to use SSH debugging on GHA.

**Comment by krlmlr** [comment]
Compilation works, but now `rstrtmgr.lib` is not found: https://github.com/duckdb/duckdb-r/actions/runs/8410314651/job/23028598267?pr=120#step:5:733 .

@jeroen: Have you seen this before? Is there a way to work around this? It only occurs with rtools 4.0, works out of the box with newer rtools.

> `c:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lrstrtmgr`

**Comment by Antonov548** [comment]
@krlmlr I have tried to build it locally. Currently I have wired error after compilation. Maybe I need to try fresh system with installed R 4.0.5:
```bash
Error in system(sprintf("%s -Pg %s", nm, shQuote(f)), intern = TRUE) : 
  '""' not found
Calls: <Anonymous> -> lapply -> FUN -> strsplit -> system
Execution halted
make: *** [C:/PROGRA~1/R/R-40~1.5/share/make/winshlib.mk:32: symbols.rds] Error 1
```

**Comment by krlmlr** [comment]
I remember seeing the same error message in another issue.

**Comment by krlmlr** [comment]
#109

**Comment by krlmlr** [comment]
The error most likely comes from here: https://github.com/r-devel/r-svn/blob/1f7e4f3f673e32efefd3b8ae2e79f77a7c690002/src/library/tools/R/sotools.R#L74

**Comment by krlmlr** [comment]
Can you set an environment variable to work around?

**Comment by krlmlr** [comment]
Or perhaps try with R 4.1 and/or another version of rtools?

**Comment by Antonov548** [comment]
> Can you set an environment variable to work around?

Setting `UserNM` helps. Thanks.

Now I have error: `could not find: rstrtmgr` which is expected. I will try take a look how it can be fixed.
Also, it always recompile the entire project. Is something that also should be configured? Or does it recompile everything because didn't sucsefully created package.

**Comment by krlmlr** [comment]
You could try `R CMD INSTALL .` in the terminal, or set up ccache.

**Comment by krlmlr** [comment]
What value did you set `UserNM` to? Can you please help the OP in https://github.com/duckdb/duckdb-r/issues/109?

**Comment by krlmlr** [comment]
A fix today would have tremendous value. Thanks for looking into it!

**Comment by krlmlr** [comment]
Reopening to clean cache.

**Pull request closed without merging**
